[windows]
winhost ansible_host=10.0.2.10

[windows:vars]
ansible_connection=winrm
ansible_port=5986
ansible_user=Administrator
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
