---
- name: CIS-like hardening baseline for Windows Server 2022
  hosts: windows
  gather_facts: false
  vars_files:
    - ./vars/vars.yml

  roles:
    - 01-AccountPolicies
    - 02-2-UserRightsAssignment
    - 09-WindowsFirewall
    - 18-AdministrativeTemplates
